spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0.0"

accounts:
  message: "Welcome to Banking-App-2 LOANS related prod APIs "
  contactDetails:
    name: "Ziggy - Product Owner"
    email: "zigstar@test.com"
  onCallSupport:
    - (555) 444-3333
    - (555) 345-2345