spring:
  application:
    name: "configserver"
  profiles:
    #active: native *Used for configserver without git*
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
        git:
          uri: "https://github.com/andymartinez1/Java-Banking-App-2-Config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: "jnjkn45j2389iH8989FHJJ89y98yd89"

server:
  port: 8071